package seedu.address.ui.testutil;

import static org.junit.Assert.assertEquals;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import guitests.guihandles.EntryCardHandle;
import guitests.guihandles.EntryListPanelHandle;
import guitests.guihandles.ResultDisplayHandle;
import seedu.address.model.entry.Entry;

/**
 * A set of assertion methods useful for writing GUI tests.
 */
public class GuiTestAssert {

    private static final String LABEL_BASE_STYLE = "label";

    /**
     * Asserts that {@code actualCard} displays the same values as {@code expectedCard}.
     */
    public static void assertCardEquals(EntryCardHandle expectedCard, EntryCardHandle actualCard) {
        assertEquals(expectedCard.getId(), actualCard.getId());
        assertEquals(expectedCard.getLink(), actualCard.getLink());
        assertEquals(expectedCard.getTitle(), actualCard.getTitle());
        assertEquals(expectedCard.getDescription(), actualCard.getDescription());
        assertEquals(expectedCard.getTags(), actualCard.getTags());
        expectedCard.getTags().forEach(tag ->
                assertEquals(expectedCard.getTagStyleClasses(tag), actualCard.getTagStyleClasses(tag))
        );
    }

    /**
     * Asserts that {@code actualCard} displays the details of {@code expectedEntry}.
     */
    public static void assertCardDisplaysEntry(Entry expectedEntry, EntryCardHandle actualCard) {
        assertEquals(expectedEntry.getTitle().fullTitle, actualCard.getTitle());
        assertEquals(expectedEntry.getDescription().value, actualCard.getDescription());
        assertEquals(expectedEntry.getLink().value.toString(), actualCard.getLink());
        assertTagsAndTagColorStylesEqual(expectedEntry, actualCard);
    }

    /**
     * Asserts that the list in {@code entryListPanelHandle} displays the details of {@code entries} correctly and
     * in the correct order.
     */
    public static void assertListMatching(EntryListPanelHandle entryListPanelHandle, Entry... entries) {
        for (int i = 0; i < entries.length; i++) {
            entryListPanelHandle.navigateToCard(i);
            assertCardDisplaysEntry(entries[i], entryListPanelHandle.getEntryCardHandle(i));
        }
    }

    /**
     * Asserts that the list in {@code entryListPanelHandle} displays the details of {@code entries} correctly and
     * in the correct order.
     */
    public static void assertListMatching(EntryListPanelHandle entryListPanelHandle, List<Entry> entries) {
        assertListMatching(entryListPanelHandle, entries.toArray(new Entry[0]));
    }

    /**
     * Asserts the size of the list in {@code entryListPanelHandle} equals to {@code size}.
     */
    public static void assertListSize(EntryListPanelHandle entryListPanelHandle, int size) {
        int numberOfPeople = entryListPanelHandle.getListSize();
        assertEquals(size, numberOfPeople);
    }

    /**
     * Asserts the message shown in {@code resultDisplayHandle} equals to {@code expected}.
     */
    public static void assertResultMessage(ResultDisplayHandle resultDisplayHandle, String expected) {
        assertEquals(expected, resultDisplayHandle.getText());
    }

    /**
     * Returns the color style for {@code tagName}'s label. The tag's color is determined by looking up the color
     * in {@code EntryCard#TAG_COLOR_STYLES}, using an index generated by the hash code of the tag's content.
     */
    private static String getTagColorStyleFor(String tagName) {
        switch (tagName) {

        case "classmates":
            return "pink";

        case "owesMoney":
            return "lightBlue";

        case "colleagues":
            return "deepOrange";

        case "neighbours":
            return "gray";

        case "family":
            return "red";

        case "friend":
            return "amber";

        case "friends":
            return "lightBlue";

        case "husband":
            return "gray";

        case "tech":
            return "cyan";

        case "science":
            return "pink";

        case "nus":
            return "yellow";

        case "soc":
            return "gray";

        case "engineering":
            return "amber";

        case "award":
            return "gray";

        case "amazon":
            return "gray";

        case "Carl":
            return "lightBlue";

        default:
            throw new AssertionError(tagName + " does not have a color assigned.");
        }
    }

    /**
     * Asserts that the tags in {@code actualCard} matches all the tags in {@code expectedEntry} with the correct
     * color.
     */
    private static void assertTagsAndTagColorStylesEqual(Entry expectedEntry, EntryCardHandle actualCard) {

        // assert tags equal
        List<String> expectedTags = expectedEntry
                .getTags()
                .stream()
                .map(tag -> tag.tagName)
                .collect(Collectors.toList());
        List<String> actualTags = actualCard.getTags();
        assertEquals(expectedTags, actualTags);

        // assert tag color styles correct
        expectedTags.forEach(tag -> {
            List<String> expectedTagStyleClasses = Arrays.asList(LABEL_BASE_STYLE, getTagColorStyleFor(tag));
            List<String> actualTagStyleClasses = actualCard.getTagStyleClasses(tag);
            assertEquals(expectedTagStyleClasses, actualTagStyleClasses);
        });

    }

}
