= Qi Ji - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: README

== Overview

README is an integrated link manager and web feed aggregator application.

== Summary of contributions

=== *Major enhancement*: I added web syndication(RSS/Atom) support in README.
** Background: RSS and Atom achieve the purpose of web syndication. They are well-established Web syndication formats which lets users to subscribe to content sources.
** Justification: With support for web syndication the user can subscribe to sources of content that they care about, and have the content delivered to them.
** Highlights: This enhancement requires significant architectural changes in the base link management application. It required an in-depth analysis of design considerations.
** Credits: The https://rometools.github.io/rome/[ROME] library is used to the heavy lifting in parsing web feeds.

=== *Minor enhancement*: added a counter in status bar showing how many entries are listed
** Quality-of-life improvement.

=== *Code contributed*
** https://github.com/CS2103-AY1819S2-W10-1/main/pull/33[Initial RSS support]
** Architectural changes
https://github.com/CS2103-AY1819S2-W10-1/main/pull/80[#80]
https://github.com/CS2103-AY1819S2-W10-1/main/pull/107[#107]
** https://github.com/CS2103-AY1819S2-W10-1/main/pull/114[Feeds management]

=== *Other contributions*:

* Project Management:
** managed release v1.1
* Community
** PRs reviewed (with non-trivial review comments):
https://github.com/CS2103-AY1819S2-W10-1/main/pull/37[#37]
https://github.com/CS2103-AY1819S2-W10-1/main/pull/77[#77]
https://github.com/CS2103-AY1819S2-W10-1/main/pull/106[#106]
** Non-trivial contributions to forum discussions:
https://github.com/nus-cs2103-AY1819S2/forum/issues/5[#5]
https://github.com/nus-cs2103-AY1819S2/forum/issues/47[#47]
https://github.com/nus-cs2103-AY1819S2/forum/issues/51[#51]
https://github.com/nus-cs2103-AY1819S2/forum/issues/72[#72]
** Tools:
*** Integrated third party library (ROME) to the project.
https://github.com/CS2103-AY1819S2-W10-1/main/pull/33[#33]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=bingfeedfeeds]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=feedsubscription]
